import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "tailwindcss/tailwind.css"; // Import your Tailwind CSS styles
import "daisyui/dist/full.css"; // Import daisyUI styles
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en" data-theme="cupcake">
        <body className={inter.className}>{children}</body>
      </html>
    </>
  );
}
